version: '3.7'

services:
  app:
    build:
      context: .
    depends_on:
      - redis
      - mysql
    env_file:
      - ./.env
    environment:
      DB_HOST: mysql
      REDIS_HOST: redis
    volumes:
      - app-data:/var/www/html

  echo:
    image: oanhnn/laravel-echo-server:latest
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      LARAVEL_ECHO_SERVER_PORT: 8443
    ports:
      - 8443:8443

  nginx:
    image: nginx:stable
    depends_on:
      - app
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - app-data:/var/www/html
    ports:
      - 80:80

  redis:
    image: redis:6

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: unit3d
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  app-data:
  db-data:
